### ISSUE TITLE
JSI Limitations

### ISSUE THREAD

**Issue by kylecesmat** [margelo/react-native-bignumber#42]
Hello!

I'm attempting to debug an application in iOS using Chrome, and hitting a JSI error. Curious, is there any way around this?

Thinking about possibly wrapping the native class and falling back to BN.js when JSI is not enabled (debug only). Wondering if there are other solutions that have been considered?

**Comment by Szymon20000** [comment]
We could do it this way. Meanwhile, you could debug it using safari (if iOS) or Flipper if you use Hermes.

**Comment by kylecesmat** [comment]
Thinking through this more, I think my current path forward is to just fall back to non-native BN.js w/ a warning in our application code. I'll leave it to you as the author to decide if this should be default behavior in the library.

Might be worthwhile adding the similar limitations verbiage from the mmkv module https://github.com/mrousavy/react-native-mmkv#limitations

Thanks for your quick response and a great lib! :)
