### ISSUE TITLE
Points to old/wrong namespace [Android]

### ISSUE THREAD

**Issue by Kida007** [margelo/react-native-bignumber#53]
Android throws an runtime Error while loading the C++ library : 

```
Didn't find class "com.reactnative bignumber.BigNumber Module"
```
I see we recently changed the namespace to com.margelo.bignumber . maybe something was missed ( just an assumption). Open to propose a fix creating a PR but need some initial pointers 😅

PS : thanks for the amazing libraries and OSS work . Team Margelo 💙

**Comment by mrousavy** [comment]
Uhm, whoops? Can you submit a PR that fixes this naming issue?

**Comment by Kida007** [comment]
Hey @mrousavy sorry i almost forgot about it. but looks like it was fixed. thanks for the amazing work. much appreciated.
